Feature/footnote popover
evolvedbinary/hsg-shell pull request #8
Opened 2022-08-02 21:17 UTC by yamahito

2022-08-02 22:11 UTC, yamahito commented
@ccheraa can you please add any documentation, add @joewiz and an internal review, then mark as ready for review.  Thanks!

2022-08-09 10:57 UTC, plutonik-a requested changes

2022-08-09 10:57 UTC, plutonik-a commented on tests/specs/footnote/uat_footnote_popover.spec.js
> +      Page.getElement('.popover').moveTo();
`moveTo()` without arguments is failing currently.
This is the error:
```
from invalid argument: 'y' must be an int
  (Session info: chrome=104.0.5112.79)
```
That means running Chrom / Chromedriver v104 with current test framework at version `@wdio/cli@5.18.6` is probably not supported.

2022-08-09 14:22 UTC, plutonik-a commented
Footnote number should be shown in the popover.

2022-08-09 14:27 UTC, plutonik-a requested changes
See https://github.com/evolvedbinary/hsg-shell/pull/8#issuecomment-1209448912

2022-09-01 11:17 UTC, plutonik-a requested changes
I’ve rerun the tests - 11 are still failing. Could you try to fix these by specifying scrollIntoView with scrollIntoView({behavior: "smooth", block: "center", inline: "center"}), see https://github.com/evolvedbinary/hsg-shell/blob/bc1a52c2f46fea05f075692934b1f12cdfd57dc0/tests/specs/UI-components/uat_tooltip.spec.js#L58-L66.

2022-09-12 12:37 UTC, plutonik-a approved these changes

2022-09-13 00:50 UTC, merged